---
title: SJ&P
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    author: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: authors
  values:
    position: 
    image: 
permalink: pretty
